import Foundation

enum SCPlanTableA {
    static let plans: [SCPlan] = [

        scplan("sermon-mount",
               "Sermon on the Mount",
               "Ten days on a hillside",
               .wisdom,
               "The longest stretch of teaching in the Gospels, taken a little at a time. Ten days move through the Beatitudes, the sayings about salt and light, prayer, money, worry and the two builders. The aim is not to master it but to sit with it and let it work slowly.",
               [
                scday("Blessed",
                      ["Matthew 5:3-6", "Matthew 5:7-10"],
                      "The sermon opens by congratulating the wrong people: the poor in spirit, the mourners, the meek, the ones still hungry for something right. Nobody in that crowd would have called them fortunate. Then come the merciful and the peacemakers, and the list turns from what you lack toward what you might give. Read it slowly. Notice which line you would rather skip, and stay there a moment."),
                scday("Salt and light",
                      ["Matthew 5:13", "Matthew 5:14-16"],
                      "Salt and lamps are useful things, not decorative ones. Salt that has lost its savour is simply thrown out on the path, and a lamp under a basket is a small absurdity. What is striking is how ordinary the images are. Nothing here asks for a platform or a following. It asks only that whatever you actually have not be hidden away out of caution."),
                scday("Hard love",
                      ["Matthew 5:44-45", "Matthew 5:11-12"],
                      "Loving an enemy is not described as a feeling to work up. It is a set of actions: bless, do good, pray. The reason given is the weather, of all things. Sun and rain fall on the just and the unjust alike, without sorting anyone first. Then the reading turns to being spoken against unfairly, and calls that a kind of company rather than a catastrophe."),
                scday("In secret",
                      ["Matthew 6:6", "Matthew 6:9-13"],
                      "Go into your room and shut the door. Prayer here is stripped of any audience, which is a relief once you stop resenting it. Then comes the prayer itself, and it is short. Bread for today, forgiveness given and received, and a request not to be led into more than you can carry. Very little about outcomes. Mostly about who you are speaking with."),
                scday("Released",
                      ["Matthew 6:14-15", "Matthew 7:1-2"],
                      "Forgiveness and judgment are set side by side, and both come back around. The measure you hand out is the measure handed back. That sounds like a threat until you have watched somebody live for years inside their own strictness. Holding a debt requires holding on. Today asks a plain question: is there a ledger you are still keeping, and what has keeping it cost you?"),
                scday("Treasure",
                      ["Matthew 6:19-21", "Matthew 6:24"],
                      "Moth, rust and thieves are all quiet forces. Nothing dramatic takes the treasure; it simply erodes while you are not watching. The line that follows is the sharp one: where your treasure is, your heart follows after it, not the other way round. Then the plain impossibility of two masters. No one is asked to despise money here, only to notice what is quietly steering."),
                scday("Consider the birds",
                      ["Matthew 6:25-26", "Matthew 6:28-30"],
                      "The argument is made by pointing at things: sparrows that keep no barns, lilies dressed better than a king. It is not a claim that hardship never comes. It is an invitation to look outward for a minute instead of inward at the accounts. Anxiety narrows the eyes. This asks you to widen them, and to notice how much living happens without your management."),
                scday("Enough for today",
                      ["Matthew 6:33-34"],
                      "Sufficient unto the day is the evil thereof. The older phrasing means each day brings enough of its own trouble, so there is no need to borrow tomorrow's. Worry rarely stays in the present tense; it lives forward. The instruction is not to plan less but to carry less. What of tomorrow are you already holding today, and could you set it down until morning?"),
                scday("Ask",
                      ["Matthew 7:7-8", "Matthew 7:9-11", "Matthew 7:12"],
                      "Ask, seek, knock. Three verbs, each more insistent than the last, and none of them passive. The illustration is a parent who does not hand a child a stone when bread was wanted. Then the golden rule arrives almost casually, as if it followed naturally: do to others what you would want done. Perhaps it does follow. People who have been given to tend to give."),
                scday("Two builders",
                      ["Matthew 7:13-14", "Matthew 7:24-25", "Matthew 7:26-27"],
                      "Both houses in the story look finished. Both builders worked. The difference is invisible until the rain comes, and then it is the only thing that matters. The sermon ends not with a summary but with weather. It is worth asking, without any drama, what this week is actually built on, and whether the answer would hold if the weather changed."),
               ]),

        scplan("psalms-thirty",
               "Thirty Days in the Psalms",
               "A month of borrowed words",
               .praise,
               "The Psalms say everything out loud: delight, complaint, gratitude, exhaustion, awe. Thirty days walk through some of the best known of them, a few verses at a time. This one suits anyone who wants language for what they already feel but have not found words for.",
               [
                scday("The tree",
                      ["Psalms 1:1", "Psalms 1:3", "Psalms 1:6"],
                      "The book opens with a picture rather than an argument: a tree planted by water, unhurried, fruiting in its own season. Trees do not strain. They stand where they are put and draw on what is near them. The psalm also notices company, and how quietly the people we walk beside shape us. Where are your roots reaching this month, and what are they finding?"),
                scday("The heavens",
                      ["Psalms 19:1", "Psalms 8:3-4", "Psalms 24:1"],
                      "Two moods sit together here. The sky is enormous and says something without saying anything. Then the second reading looks up at the moon and the stars and asks the honest question that follows: what is a person, that anyone should bother about them. The psalm does not answer by shrinking us. Smallness and being cared for turn out not to be opposites."),
                scday("Words and thoughts",
                      ["Psalms 19:7", "Psalms 19:14"],
                      "The same psalm that started with the sky ends at the mouth. Let the words of my mouth and the meditation of my heart be acceptable. It is a modest request, and a searching one, because meditation here means what runs in the background when nobody is listening. Speech is downstream of that. Today you might just notice what your mind rehearses when it is idle."),
                scday("The shepherd",
                      ["Psalms 23:1", "Psalms 23:2"],
                      "I shall not want does not mean I will never wish for anything. It means I will not lack. The line that follows is stranger than it looks: he makes me to lie down. Rest is not always chosen; sometimes it is arranged for us, and sheep do not lie down where they feel unsafe. Green pastures and still waters are a description of trust, not scenery."),
                scday("Through the valley",
                      ["Psalms 23:3", "Psalms 23:4", "Psalms 29:11"],
                      "The psalm does not say around the valley. It says through, and the walking continues. Notice the pronoun shift too, from he leads to thou art with me. Danger changes the grammar from talking about God to talking to him. The rod and staff are working tools of a shepherd, not ornaments. Comfort here is practical, close at hand, and does not require the valley to end first."),
                scday("A table set",
                      ["Psalms 23:5", "Psalms 23:6"],
                      "A table prepared in the presence of enemies is an odd, brave image. The enemies are still there; the meal happens anyway. There is oil, and a cup that runs over, which is the language of a host who does not measure carefully. The psalm ends with goodness and mercy following after, as though they were behind us the whole time, catching up."),
                scday("Light and strength",
                      ["Psalms 27:1", "Psalms 27:14", "Psalms 28:7"],
                      "The Lord is my light and my salvation, whom shall I fear. It is a question, not a boast, and questions can be asked on days when you are not certain. Then the psalm does something honest: it tells you to wait, and repeats it, as if once was not enough. Waiting of courage, not waiting of resignation. There is a difference, and today may be the day to learn it."),
                scday("Morning comes",
                      ["Psalms 30:5", "Psalms 126:5", "Psalms 143:8"],
                      "Weeping may endure for a night, but joy cometh in the morning. Not a promise that grief is short, but a reminder that nights end. The second reading holds sowing in tears together with reaping in joy, which is farming language: something is happening underground that you cannot see. Then a small request, to hear kindness in the morning. Mornings are worth asking for."),
                scday("Taste and see",
                      ["Psalms 34:8", "Psalms 34:4", "Psalms 146:5"],
                      "Taste and see is a peculiar instruction, because taste cannot be done at a distance. You cannot conclude that bread is good by studying it. The psalm before it is plainer still: I sought, and he heard, and delivered me from all my fears. Notice the order. Seeking came first, and the fears were not argued away; they were lifted off."),
                scday("Near the broken",
                      ["Psalms 34:18", "Psalms 147:3"],
                      "The Lord is nigh unto them that are of a broken heart. Not distant from them, waiting for repair, but near. The second verse says he binds up wounds, which is the work of a field dressing rather than a lecture. Neither line asks the broken person to explain themselves. If today you are in that condition, the reading does not ask you to be anywhere else."),
                scday("Commit the way",
                      ["Psalms 37:3", "Psalms 37:4", "Psalms 37:5"],
                      "Three short verbs across three verses: trust, delight, commit. Commit thy way is a traveller's phrase, handing over the route rather than the destination. Delight in the older sense means to take pleasure in, not to feel enthusiastic on demand. And the promise about the desires of your heart may work in an unexpected direction, shaping what you want rather than merely delivering it."),
                scday("Ordered steps",
                      ["Psalms 37:23", "Psalms 32:8", "Psalms 25:4"],
                      "The steps of a good man are ordered, one at a time, not the whole staircase revealed at once. The second reading offers instruction and a guiding eye. Then the psalmist simply asks: shew me thy ways. There is something restful in a request that small. You are not asked to see the route today, only the next step, and to be willing to take it."),
                scday("Thirst",
                      ["Psalms 42:1", "Psalms 63:1", "Psalms 145:18"],
                      "As the hart panteth after the water brooks. A deer at the end of a long run, not a person calmly reflecting. The next psalm is drier still: a thirsty land where no water is. Spiritual dryness is treated here as a real condition, described rather than scolded. And the last line is quiet reassurance: nearness to all who call. Thirst itself may be a kind of calling."),
                scday("Why so downcast",
                      ["Psalms 42:5", "Psalms 22:1", "Psalms 31:24"],
                      "The psalmist speaks to himself, which is worth noticing. Why art thou cast down, O my soul. It is a conversation, not a verdict. And the collection makes room for the rawest line of all, the one about being forsaken, without editing it out. Then, at the end, courage. Not cheerfulness. Courage is what you use when the feeling has not changed yet."),
                scday("Be still",
                      ["Psalms 46:1", "Psalms 46:10", "Psalms 20:7"],
                      "Be still is often read as calm down. The older sense is closer to cease, let your hands drop, stop working at it. That is harder. The psalm around it is loud with mountains moving and waters roaring, so the stillness is not the absence of trouble. Some trust in chariots, says the last reading. Most of us have a chariot of some kind."),
                scday("A clean heart",
                      ["Psalms 51:10", "Psalms 51:17", "Psalms 32:1"],
                      "Create in me a clean heart. Create is a strong word; the psalmist is not asking for a wash but for something made new. Then comes the line about a broken and contrite spirit being what is actually wanted, which overturns a great deal of religious effort. And the last reading calls the forgiven person happy. Not merely cleared. Happy, in the old plain sense of fortunate."),
                scday("Cast the burden",
                      ["Psalms 55:22", "Psalms 56:3", "Psalms 94:19"],
                      "Cast thy burden upon the Lord. Cast is a throwing word, deliberate and one-directional, unlike the way most of us set a worry down and then pick it back up. The middle verse is almost childlike: what time I am afraid, I will trust. It allows for the fear. Then a phrase about thoughts multiplying inside, and comfort meeting them there."),
                scday("The higher rock",
                      ["Psalms 61:2", "Psalms 62:8", "Psalms 9:9"],
                      "Lead me to the rock that is higher than I. The request assumes you cannot climb it alone, which is the honest part. Then an invitation to pour out your heart, which is not tidy language; pouring leaves nothing back. A refuge in times of trouble is the last image. Not a refuge from having trouble. A place to be while it lasts."),
                scday("Strength of my heart",
                      ["Psalms 73:26", "Psalms 84:11", "Psalms 16:11"],
                      "My flesh and my heart faileth. The psalmist says it plainly, without apology, and then says that something else holds when he does not. The second reading calls God a sun and shield, warmth and protection in one breath. And the last speaks of a path of life and fullness of joy. Failing and being sustained can be true on the same day."),
                scday("Number the days",
                      ["Psalms 90:12", "Psalms 86:11"],
                      "Teach us to number our days, that we may apply our hearts unto wisdom. Counting the days is not a morbid exercise here; it is what makes a day worth something. The second request asks for an undivided heart, and that may be the harder ask. Most days are lost less to shortness than to being scattered. What would today look like if it were counted?"),
                scday("Under the wings",
                      ["Psalms 91:1", "Psalms 91:4", "Psalms 91:11"],
                      "The secret place, the shadow, feathers and wings. The imagery is domestic and small rather than fortress-like, a bird covering what is under her. Alongside it sits the language of shields and of being kept in all your ways. Both pictures are offered without ranking. Some days you need the fortress. Some days what helps is the sense of being covered while you sleep."),
                scday("Mercy",
                      ["Psalms 103:8", "Psalms 103:12", "Psalms 103:13", "Psalms 86:5"],
                      "Slow to anger, and plenteous in mercy. Plenteous is not a careful word; it means there is more than enough. Then the measurement that refuses to be a measurement: as far as the east is from the west. East and west never meet, which is the point. And the tenderness of a parent toward a child is offered as the nearest human comparison anyone had."),
                scday("Bless the Lord",
                      ["Psalms 103:1", "Psalms 150:6", "Psalms 145:8"],
                      "Bless the Lord, O my soul, and all that is within me. The psalmist is again talking to himself, gathering the scattered parts and pointing them one way. Praise here is not a mood that arrives; it is something a person decides to do with what they have. The last line widens it to everything that breathes, which is a low bar and, today, one you clear."),
                scday("Give thanks",
                      ["Psalms 107:1", "Psalms 100:4", "Psalms 100:5"],
                      "O give thanks, for he is good. The reason offered is not a list of recent favours but character, which is steadier ground. Entering the gates with thanksgiving is a picture of arriving somewhere already grateful rather than waiting to be persuaded. Gratitude in these psalms is a way in, not a reward for a good week. What would you carry through the gate today?"),
                scday("This day",
                      ["Psalms 118:24", "Psalms 118:6", "Psalms 16:8"],
                      "This is the day which the Lord hath made. This one, the ordinary one, not a better one later. Rejoicing in it is not the same as liking everything in it. The verses around it are the language of someone who has decided where to stand: the Lord is on my side, I have set him always before me. Standing takes practice."),
                scday("A lamp",
                      ["Psalms 119:105", "Psalms 119:11", "Psalms 119:114"],
                      "A lamp unto my feet, and a light unto my path. An oil lamp lights the next few steps, not the horizon, which is a fair description of how guidance usually works. The second verse speaks of hiding words in the heart, keeping them where they can be reached without a book. The third calls it a hiding place. Small light, close at hand, portable."),
                scday("Lifting the eyes",
                      ["Psalms 121:1-2", "Psalms 121:7-8"],
                      "I will lift up mine eyes unto the hills. It is a traveling psalm, sung by people on a road where hills meant both destination and danger. The help named is not the hills but the one who made them. Then the going out and the coming in, the two ends of any ordinary day. Protection here is not dramatic. It is the shape of a commute."),
                scday("Unless the house",
                      ["Psalms 127:1", "Psalms 133:1", "Psalms 138:8"],
                      "Except the Lord build the house, they labour in vain that build it. The verse is not against work; it is against the exhausting belief that everything rests on your effort. Then a short line about how good it is when people live together in peace, which any household knows is a kind of building too. And a quiet confidence that what was begun will be finished."),
                scday("Waiting",
                      ["Psalms 130:5", "Psalms 40:1", "Psalms 62:5"],
                      "I wait for the Lord, my soul doth wait. Repetition here does the work that impatience usually does. The second reading says I waited patiently, and he inclined unto me, which suggests waiting is not empty time. Waiting in these psalms is active, attentive, more like watching for a light than sitting in a queue. What are you waiting on at the moment?"),
                scday("Search me",
                      ["Psalms 139:14", "Psalms 139:7-8", "Psalms 139:23-24"],
                      "Fearfully and wonderfully made. Fearfully in the older sense means with awe, not with dread. The psalm then asks where a person could possibly go to be out of reach, and finds nowhere, which can be alarming or comforting depending on the day. It ends by inviting the search rather than avoiding it. That is a brave way to close a month of reading."),
               ]),

        scplan("proverbs-decisions",
               "Proverbs for Decisions",
               "Fourteen days of practical sense",
               .wisdom,
               "Proverbs is a book about ordinary choices: what to say, who to listen to, when to wait. These fourteen readings gather the sayings that bear on decisions, from taking advice to holding your temper. Useful if something is pending and you want to think it through slowly.",
               [
                scday("Where it starts",
                      ["Proverbs 1:7", "Proverbs 9:10", "Proverbs 2:6"],
                      "The fear of the Lord is the beginning of knowledge. Fear in this older usage is nearer to awe than to terror, the posture of someone who knows they are not the largest thing in the room. Proverbs treats that as the first step in thinking clearly, not as a separate religious department. Humility comes before information. It is a strange place to start a book of practical advice."),
                scday("Lean not",
                      ["Proverbs 3:5-6", "Proverbs 16:9"],
                      "Lean not unto thine own understanding. The verse does not say stop understanding; leaning is the issue, putting all your weight on a judgment made from limited information. The second reading is gentler than it first sounds: a person plans the way, and the steps are directed. Planning is assumed. What is questioned is the certainty we attach to our plans while making them."),
                scday("Get counsel",
                      ["Proverbs 11:14", "Proverbs 15:22", "Proverbs 12:15"],
                      "In the multitude of counselors there is safety. Proverbs keeps returning to this, which suggests it was as unpopular then as now. The sharpest line is the last: the way of a fool is right in his own eyes. Not wrong in his own eyes, right. That is what makes it hard to catch from inside. Who is allowed to disagree with you at the moment?"),
                scday("Commit the work",
                      ["Proverbs 16:3", "Proverbs 19:21"],
                      "Commit thy works, and thy thoughts shall be established. The order is interesting. Handing over the work comes first, and the settling of the mind follows, rather than waiting until you feel settled before you act. The second verse allows for many plans in a heart and still expects one outcome. That is not fatalism. It is permission to hold your plans loosely."),
                scday("Guard the heart",
                      ["Proverbs 4:23", "Proverbs 4:7"],
                      "Keep thy heart with all diligence, for out of it are the issues of life. Issues here means what flows out, like water from a spring. Decisions are downstream of something older and quieter. That is why the book keeps talking about attention and company rather than technique. Before the next choice, it may be worth asking what has been going into the spring lately."),
                scday("Fewer words",
                      ["Proverbs 10:19", "Proverbs 15:1", "Proverbs 12:25", "Proverbs 18:21"],
                      "In the multitude of words there wanteth not sin. Wanteth means is lacking, so the sense is that talking a great deal eventually goes wrong somewhere. Then the famous soft answer that turns away wrath, and the observation that a good word makes a heavy heart glad. Speech is treated here as something with weight and consequence. Today might be a day for saying slightly less."),
                scday("Slow to anger",
                      ["Proverbs 14:29", "Proverbs 16:32"],
                      "He that is slow to wrath is of great understanding. Anger is not condemned; speed is. The second verse makes an unexpected comparison, ranking the person who rules their own spirit above the one who takes a city. Cities are visible achievements. Self-command is not. Most of the decisions you regret were probably made quickly rather than made wrongly in principle."),
                scday("Before a fall",
                      ["Proverbs 16:18", "Proverbs 11:2", "Proverbs 29:23", "Proverbs 15:33"],
                      "Pride goeth before destruction, and a haughty spirit before a fall. The proverb is quoted so often that its plainness gets lost: it is a sequence, not a moral judgment. Pride arrives first, then the fall, and the gap between them can be long enough to be misread as success. Humility is offered here as the thing that comes before honour, and it is rarely comfortable."),
                scday("The fear of people",
                      ["Proverbs 29:25", "Proverbs 18:10"],
                      "The fear of man bringeth a snare. A snare is a trap you walk into rather than one that chases you. Worrying about what people will think does not usually announce itself as fear; it feels like being sensible. The second reading offers a different place to stand, a strong tower. Whose opinion is currently doing the most steering in the decision in front of you?"),
                scday("Company",
                      ["Proverbs 13:20", "Proverbs 27:17", "Proverbs 17:17"],
                      "He that walketh with wise men shall be wise. Walking is the verb, not studying. Whatever you spend time near, you slowly become. Iron sharpening iron is a noisy image, with friction in it; sharpening is not the same as agreeing. And the friend who loves at all times is the one who stays when the decision goes badly. Those are three different gifts."),
                scday("Tomorrow",
                      ["Proverbs 27:1", "Proverbs 6:6", "James 4:13-15"],
                      "Boast not thyself of to morrow, for thou knowest not what a day may bring forth. Set against it is the ant, who stores in summer without being told. Proverbs is not against planning; it is against certainty. The passage in James says the same in plainer words. You may do all the preparing you like, provided you hold the calendar with an open hand."),
                scday("Rising again",
                      ["Proverbs 24:16", "Proverbs 28:13", "Proverbs 3:11-12"],
                      "A just man falleth seven times, and riseth up again. The falling is expected. What distinguishes him is the getting up, and the count suggests it is a pattern rather than an accident. Covering a fault, says the next verse, keeps you stuck; admitting it opens something. And correction is framed as a sign of care. That reframing is hard to accept while it is happening."),
                scday("Speaking for others",
                      ["Proverbs 31:8-9", "Proverbs 25:21", "Proverbs 19:11"],
                      "Open thy mouth for the dumb, meaning those who have no voice in the matter. It is one of the few places Proverbs asks for speech rather than restraint. Then a startling instruction about feeding an enemy who is hungry, which sidesteps the argument entirely. And passing over a transgression is called glory, not weakness. Some decisions are about who else is in the room."),
                scday("The widening path",
                      ["Proverbs 4:18", "Proverbs 25:11", "Proverbs 22:1"],
                      "The path of the just is as the shining light, that shineth more and more unto the perfect day. It is a slow image, dawn rather than a switch. The book ends this stretch with small things: a word spoken well, a good name kept. Neither is a decision made once. Both are made in the way a great many ordinary days are handled."),
               ]),

        scplan("when-anxious",
               "When You Are Anxious",
               "Seven short readings for restless nights",
               .fear,
               "Seven days for a mind that will not settle. The readings do not argue anxiety away or treat it as a failure; they sit beside it with older words. Short passages, one small idea each, meant for evenings when thinking harder has stopped helping.",
               [
                scday("Careful for nothing",
                      ["Philippians 4:6-7", "1 Peter 5:6-7"],
                      "Be careful for nothing is easy to misread. Careful in older English means full of care, weighed down, anxious. So the line is not telling you to be careless but to stop carrying. What follows is practical: name the thing, ask, and add thanks. The peace described is said to pass understanding, which may mean it arrives before the situation makes sense."),
                scday("Enough for today",
                      ["Matthew 6:33-34", "Matthew 6:25-26"],
                      "Take no thought for the morrow, in the older sense of taking anxious thought, not of failing to plan. Each day is said to bring enough of its own. The birds are mentioned because they are visible and unbothered, not because life is easy. Anxiety mostly lives in the future tense. Tonight, see whether you can put tomorrow down until tomorrow."),
                scday("Fear not",
                      ["Isaiah 41:10", "Isaiah 41:13", "Deuteronomy 31:6"],
                      "Fear thou not, for I am with thee. The reason offered is never that the danger was imaginary. It is presence. Twice the image is a hand taking hold of a right hand, which is what you do with someone who is unsteady rather than someone who is wrong. Then the older promise of not being forsaken. Notice how physical this comfort is."),
                scday("Through the water",
                      ["Isaiah 43:1", "Isaiah 43:2", "Psalms 46:1"],
                      "When thou passest through the waters, I will be with thee. Again through, not around, and the fire is not said to be extinguished. What changes is company, not weather. The passage begins by saying you are called by name, which is the opposite of being a case or a number. A present help in trouble is the phrase in the psalm. Present, and in."),
                scday("A settled mind",
                      ["Isaiah 26:3", "Philippians 4:8-9"],
                      "Thou wilt keep him in perfect peace, whose mind is stayed on thee. Stayed means propped, leaning on something solid. The verse links peace to where attention rests rather than to circumstances improving. Then a list of things worth thinking about: true, honest, just, pure, lovely. It reads like a suggestion for what to feed a mind at eleven at night."),
                scday("Not fear",
                      ["2 Timothy 1:7", "Psalms 94:19", "John 14:27"],
                      "God hath not given us the spirit of fear, but of power, and of love, and of a sound mind. A sound mind here means one that is whole and steady, not one that never trembles. The psalm speaks of thoughts multiplying inside, which is exactly the two-in-the-morning experience. Then peace is offered, and described as unlike the kind the world hands out."),
                scday("Rest",
                      ["Matthew 11:28-30", "Psalms 55:22", "Psalms 62:8"],
                      "Come unto me, all ye that labour and are heavy laden. The invitation is addressed to the tired rather than the deserving. A yoke is still work, but a shared one, cut to fit. The psalm adds a throwing word, cast, and then an even plainer one: pour out your heart. Nothing here asks you to arrive calm first. Come as you are tonight."),
               ]),

        scplan("gratitude",
               "Gratitude",
               "Three weeks of noticing",
               .thanksgiving,
               "Twenty-one days on thankfulness, which the Bible treats less as a mood than as a practice of attention. The readings move from simple thanks through contentment, generosity, and gratitude that survives a bad year. Good for anyone who suspects they have stopped noticing.",
               [
                scday("Give thanks",
                      ["1 Chronicles 16:34", "Psalms 107:1"],
                      "O give thanks unto the Lord, for he is good. The reason offered is character rather than a recent run of luck, which makes it available on ordinary days. Both verses add that his mercy endures for ever, and endures is the working word. Gratitude built on how the week went will be as unsteady as the week. Start today with something steadier than the week."),
                scday("Through the gates",
                      ["Psalms 100:4", "Psalms 100:5"],
                      "Enter into his gates with thanksgiving, and into his courts with praise. The picture is of arriving somewhere already grateful, carrying it in rather than waiting to be given a reason. Anyone who has walked into a room determined to be unimpressed knows how much the approach decides. What would it change to begin today that way, before anything in it has gone well or badly?"),
                scday("In everything",
                      ["1 Thessalonians 5:16-18", "Colossians 3:16-17"],
                      "In every thing give thanks. Note the preposition. It is in, not for, which leaves room for things that are genuinely not good and still asks what can be seen in them. Colossians ties it to whatever you do in word or deed, which is broad enough to include email and washing up. Thankfulness here is a habit of speech, not an occasion."),
                scday("Every good gift",
                      ["James 1:17", "Genesis 1:31"],
                      "Every good gift and every perfect gift is from above, with whom is no variableness. Variableness means change, the flickering of a shadow as light moves. The claim is that the source is steady even when your experience of it is not. Set beside it, the oldest verdict in the book: it was very good. Someone looked at the whole thing and was pleased."),
                scday("New every morning",
                      ["Lamentations 3:22", "Lamentations 3:23", "Psalms 143:8"],
                      "They are new every morning: great is thy faithfulness. Remarkably, the line sits in the middle of a book of laments, written by someone watching a city fall. Mercies are described as fresh rather than stored, which means yesterday's supply was never meant to cover today. The psalm asks to hear kindness in the morning. Both assume morning will come again."),
                scday("The one who returned",
                      ["Luke 17:15-16", "Psalms 103:1"],
                      "Ten were healed and one came back. The other nine did nothing wrong, exactly; they simply moved on, which is what most of us do. Gratitude requires turning around, and turning around costs time. The psalm shows the same motion inward: bless the Lord, O my soul, and all that is within me. Gathering yourself to say thank you is an act of will."),
                scday("Learned contentment",
                      ["Philippians 4:11-13", "1 Timothy 6:6-8"],
                      "I have learned, in whatsoever state I am, therewith to be content. Learned is the honest word. It was not a temperament he was born with, and the passage lists both plenty and hunger as classrooms. Timothy adds that godliness with contentment is great gain, then sets the bar at food and covering. That is a low bar and a surprisingly hard one."),
                scday("Never enough",
                      ["Ecclesiastes 5:10", "Luke 12:15"],
                      "He that loveth silver shall not be satisfied with silver. The observation is about appetite rather than money: some hungers grow by being fed. Luke puts it plainly, that a life does not consist in the abundance of things possessed. Neither passage condemns having. Both notice how quietly the scale resets, so that what once seemed like plenty stops registering at all."),
                scday("Remember the road",
                      ["Deuteronomy 8:2", "Deuteronomy 8:3"],
                      "Thou shalt remember all the way which the Lord thy God led thee. Remembering is given as an instruction because forgetting is the default. Forty years in a wilderness is not an obvious thing to be grateful for, and the passage does not pretend otherwise. It points instead at what was learned there about daily bread. Looking back at a hard stretch, what did it actually teach you?"),
                scday("Made",
                      ["Psalms 139:14", "Psalms 8:3-4"],
                      "Fearfully and wonderfully made. Fearfully in the old sense means with awe rather than with dread. It is an unfashionable thing to say about your own body on a day when it aches or disappoints you. The other psalm looks upward at the moon and stars and lands on the same surprise from the opposite direction: that anyone should be mindful of us at all."),
                scday("Sky and season",
                      ["Psalms 19:1", "Ecclesiastes 3:11"],
                      "The heavens declare, without words, to no particular audience. Then Ecclesiastes says something stranger: he hath made every thing beautiful in his time, and set the world in their heart. Some read that last phrase as a sense of eternity planted in us, which would explain the restlessness. Beauty and dissatisfaction may be nearer relatives than we assume. Look up at some point today."),
                scday("Cheerfully",
                      ["2 Corinthians 9:6-7", "2 Corinthians 9:8"],
                      "God loveth a cheerful giver. The Greek behind cheerful is the root of our word hilarious, which suggests something lighter than duty. The passage is careful to rule out giving grudgingly or under pressure, and that ruling out is the kindest part. Then the promise of sufficiency, which is not the promise of surplus. Enough is treated here as a genuinely good outcome."),
                scday("More blessed to give",
                      ["Acts 20:35", "1 Timothy 6:17-19"],
                      "It is more blessed to give than to receive. The line is quoted so often that its oddness fades; almost nobody experiences it as obviously true in the moment. Timothy adds a warning against trusting in uncertain riches, and then, unexpectedly, says God gives us things richly to enjoy. Enjoyment and open hands are not set against each other. Both are assumed."),
                scday("Joy as strength",
                      ["Nehemiah 8:10", "Psalms 16:11"],
                      "The joy of the Lord is your strength. It was said to people weeping over what they had just heard read aloud, and the instruction included eating well and sending portions to those who had nothing prepared. Joy in that scene is practical and shared. The psalm adds fulness of joy and pleasures, words rarely associated with religion, and offers them without embarrassment."),
                scday("Thankful for people",
                      ["Philemon 1:7", "3 John 1:4", "1 Thessalonians 5:11"],
                      "We have great joy and consolation in thy love, because the bowels of the saints are refreshed by thee. Bowels is the old word for the deep inward part, where you feel things; the sense is that people were genuinely revived by him. These are letters that stop to say thank you by name. Who has refreshed you lately, and have you told them?"),
                scday("Rooted",
                      ["Colossians 2:6-7", "Colossians 3:14-15"],
                      "Rooted and built up, stablished in the faith, abounding therein with thanksgiving. Two images at once, a plant and a building, both of them slow. Thanksgiving is named as what abundance looks like, rather than as a duty added afterwards. The later verse asks that peace rule in the heart, and adds, almost in passing, be ye thankful. It keeps arriving as an instruction."),
                scday("Even if not",
                      ["Habakkuk 3:17-18", "Job 1:21"],
                      "Although the fig tree shall not blossom, neither shall fruit be in the vines. The list continues until nothing is left standing, and only then comes the yet. This is gratitude with the harvest failed, which is a different thing from gratitude at a full table. Job says something similar with everything gone. Neither man pretends. That is what makes the yet worth hearing."),
                scday("Mercy remembered",
                      ["Micah 7:18", "Psalms 103:12"],
                      "Who is a God like unto thee, that pardoneth iniquity, and delighteth in mercy. Delighteth is the surprising verb; not tolerates, not permits. The psalm measures the distance with something that cannot be measured, east from west, two directions that never meet. If you have been carrying an old thing, today's reading suggests it may already be further away than you have allowed yourself to believe."),
                scday("Whatever you do",
                      ["1 Corinthians 10:31", "Ecclesiastes 9:10"],
                      "Whether therefore ye eat, or drink, or whatsoever ye do, do all to the glory of God. The examples chosen are deliberately small. Eating and drinking are not ceremonies. Ecclesiastes adds that whatever your hand finds to do should be done with your might, which is the opposite of half-attention. Gratitude and attention keep turning out to be the same habit wearing different clothes."),
                scday("Counted days",
                      ["Psalms 90:12", "Psalms 118:24"],
                      "Teach us to number our days, that we may apply our hearts unto wisdom. Counting is what makes a thing valuable; we do not count what we assume is endless. Then the other psalm names this particular day as made, and worth rejoicing in. Not a better day later. This one, with its ordinary weather and unfinished tasks. Three weeks in, that may be the whole lesson."),
                scday("A blessing to carry",
                      ["Numbers 6:24-26", "Psalms 150:6"],
                      "The Lord bless thee, and keep thee, and make his face shine upon thee. It is one of the oldest blessings we have, spoken over people at the end of a gathering so they would carry it out. A shining face simply means being glad to see someone. The last line widens it to everything that breathes. That includes you, today, without any qualification."),
               ]),

        scplan("patience",
               "Patience",
               "Seven days on waiting well",
               .endurance,
               "Patience in these passages is not passivity; it is the strength to stay with something unfinished. Seven readings look at delay, slow growth, quick tempers and the long race. For anyone in the middle of something that has taken longer than expected.",
               [
                scday("What trouble makes",
                      ["Romans 5:3-5", "James 1:2-4"],
                      "Tribulation worketh patience. Worketh means produces, the way pressure produces something in metal. Neither passage claims the trouble is good, only that something is being made in it. James adds a strange instruction about counting it joy, which is an accounting word rather than a feeling. You are asked to reckon what is happening, not to enjoy it."),
                scday("The farmer",
                      ["James 5:7-8", "Habakkuk 2:3"],
                      "Behold, the husbandman waiteth for the precious fruit of the earth. A farmer's waiting is not idleness; it is work done and then a season that cannot be hurried. Nothing about digging the seed up to check. The second reading says the vision is for an appointed time and will not lie, even if it tarries. Slow is not the same as failing."),
                scday("Renewed",
                      ["Isaiah 40:31", "Psalms 27:14"],
                      "They that wait upon the Lord shall renew their strength. The order matters: waiting comes before the renewing, which is the part nobody likes. Then the picture descends from eagles to running to walking, as though the last one were the achievement. Some seasons you fly. Most seasons you walk and do not faint. The psalm simply says be of good courage, and says it twice."),
                scday("Slow to speak",
                      ["James 1:19-20", "Proverbs 14:29", "Proverbs 16:32"],
                      "Swift to hear, slow to speak, slow to wrath. Three speeds, carefully ordered. The passage does not forbid anger; it slows it down, on the grounds that the wrath of a person rarely produces what it intends. Proverbs agrees, and adds that ruling your own spirit outranks capturing a city. Patience, in these lines, is mostly a matter of timing."),
                scday("Long-suffering",
                      ["1 Corinthians 13:4-5", "Colossians 3:12-13"],
                      "Charity suffereth long, and is kind. Charity is the older word for love, and suffereth long simply means it puts up with a great deal for a long time. The list that follows is unglamorous: not easily provoked, keeping no record. Colossians adds forbearing one another, which assumes there will be something to forbear. Patience here is aimed at people, not circumstances."),
                scday("In due season",
                      ["Galatians 6:7-9", "Ecclesiastes 3:1"],
                      "Let us not be weary in well doing, for in due season we shall reap, if we faint not. Due season is the honest phrase; it is not soon, and it is not never. Sowing and reaping happen at different times, which is the whole difficulty. Ecclesiastes puts it more broadly still: to every thing a season. Some things simply cannot be had early."),
                scday("The long race",
                      ["Hebrews 12:1-2", "Hebrews 12:3", "Hebrews 10:23-25"],
                      "Let us run with patience the race that is set before us. Patience and running are not usually paired, which is the point; this is distance, not a sprint. First comes laying weight down, then looking ahead rather than sideways. The passage also mentions considering someone who endured, and gathering with others. Endurance in this letter is rarely something done alone."),
               ]),

        scplan("courage",
               "Courage",
               "Seven days for a hard thing",
               .endurance,
               "Seven readings for a decision you have been avoiding or a situation that asks more of you than you feel you have. The people in these passages are mostly frightened; what they are given is company and a next step rather than a feeling of bravery.",
               [
                scday("Be strong",
                      ["Joshua 1:9", "Deuteronomy 31:6"],
                      "Be strong and of a good courage. It is said as a command, which is odd until you notice it is repeated, as though it needed saying more than once to a man who was clearly afraid. The reason attached is not a promise of easy ground but of company on it. Courage here is not a temperament. It is something you are told, and then do."),
                scday("More with us",
                      ["Joshua 1:5", "2 Kings 6:16", "2 Chronicles 20:12"],
                      "They that be with us are more than they that be with them. The servant counting the enemy was not wrong about the number; he was working from an incomplete picture. Alongside it sits one of the most honest prayers anywhere: we have no might, neither know we what to do, but our eyes are upon thee. Admitting that is not the end of courage. It is often the beginning."),
                scday("The fear of people",
                      ["Proverbs 29:25", "Psalms 118:6", "Psalms 27:1"],
                      "The fear of man bringeth a snare. Much of what passes for caution is really concern about being judged, and it is hard to spot because it feels reasonable. The psalms answer it twice, both times with a question rather than a slogan: what can man do unto me, whom shall I fear. Questions leave room for the fear to still be there."),
                scday("But if not",
                      ["Daniel 3:17-18", "Daniel 6:10"],
                      "But if not. Three words that carry the whole weight. The three men say they believe they can be delivered, and then say they will not change course even if they are not. That is a different kind of confidence from expecting a good outcome. And Daniel, hearing the decree, goes home and opens the window as usual. Courage sometimes looks like an unchanged routine."),
                scday("For such a time",
                      ["Esther 4:14", "Judges 6:12"],
                      "Who knoweth whether thou art come to the kingdom for such a time as this. It is put as a question, not a certainty, which is more useful; Esther still has to decide. Gideon is greeted as a mighty man of valour while hiding in a winepress, which is either irony or the point. People are sometimes addressed by what they will be rather than what they are."),
                scday("Small beginnings",
                      ["Zechariah 4:6", "Zechariah 4:10", "1 Samuel 17:47"],
                      "Who hath despised the day of small things. The rebuilt temple looked disappointing to people who remembered the first one, and the answer given is not to argue about scale. Not by might, nor by power. The shepherd boy in the valley makes the same case with a sling. Small beginnings are easy to be embarrassed by. That embarrassment stops more things than opposition does."),
                scday("Take heart",
                      ["John 16:33", "1 Corinthians 16:13-14", "2 Timothy 1:7"],
                      "In the world ye shall have tribulation, but be of good cheer. The first half is not softened, which is why the second half can be trusted. Then a short set of instructions: watch, stand fast, be strong, and let all things be done with charity, the older word for love. Courage without kindness turns into something else. The last line rules out fear as the source."),
               ]),

    ]
}
