import Foundation

enum SCVerseTableA {
    static let entries: [SCVerse] = [

        // MARK: - Psalms

        scv("Psalms", 1, 1, 1, "Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the seat of the scornful.", "The psalter opens by watching where a life slows down and settles.", [.wisdom, .guidance]),
        scv("Psalms", 1, 3, 3, "And he shall be like a tree planted by the rivers of water, that bringeth forth his fruit in his season; his leaf also shall not wither; and whatsoever he doeth shall prosper.", "A tree does not hurry its fruit, and neither does a settled life.", [.endurance, .hope]),
        scv("Psalms", 1, 6, 6, "For the LORD knoweth the way of the righteous: but the way of the ungodly shall perish.", "Two roads are contrasted, and one of them is simply known.", [.guidance, .justice]),
        scv("Psalms", 8, 3, 4, "When I consider thy heavens, the work of thy fingers, the moon and the stars, which thou hast ordained; What is man, that thou art mindful of him? and the son of man, that thou visitest him?", "A night sky can make a person feel small and remembered at once.", [.humility, .praise]),
        scv("Psalms", 9, 9, 9, "The LORD also will be a refuge for the oppressed, a refuge in times of trouble.", "Refuge is offered here to those with the least power to demand it.", [.justice, .hope]),
        scv("Psalms", 16, 8, 8, "I have set the LORD always before me: because he is at my right hand, I shall not be moved.", "Steadiness is described as a matter of attention, kept up daily.", [.endurance, .guidance]),
        scv("Psalms", 16, 11, 11, "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.", "David closes a psalm about safety by speaking of gladness instead.", [.hope, .praise]),
        scv("Psalms", 19, 1, 1, "The heavens declare the glory of God; and the firmament sheweth his handywork.", "Creation is pictured as speech that needs no translation.", [.praise, .wisdom]),
        scv("Psalms", 19, 7, 7, "The law of the LORD is perfect, converting the soul: the testimony of the LORD is sure, making wise the simple.", "The psalm turns from the sky to the written word without a break.", [.wisdom, .guidance]),
        scv("Psalms", 19, 14, 14, "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer.", "A prayer often used to close a service, and to begin a day.", [.humility, .guidance]),
        scv("Psalms", 20, 7, 7, "Some trust in chariots, and some in horses: but we will remember the name of the LORD our God.", "Written before a battle, when the odds were being counted aloud.", [.fear, .hope]),
        scv("Psalms", 22, 1, 1, "My God, my God, why hast thou forsaken me? why art thou so far from helping me, and from the words of my roaring?", "The question is left in the book without being smoothed over.", [.doubt, .fear]),
        scv("Psalms", 23, 1, 1, "The LORD is my shepherd; I shall not want.", "The whole psalm rests on this first clause.", [.provision, .rest]),
        scv("Psalms", 23, 2, 2, "He maketh me to lie down in green pastures: he leadeth me beside the still waters.", "Sheep will not lie down while anxious, which is the quiet point here.", [.rest, .provision]),
        scv("Psalms", 23, 3, 3, "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake.", "Restoring comes before leading, in that order.", [.rest, .guidance]),
        scv("Psalms", 23, 4, 4, "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.", "Company in the valley, not a detour around it.", [.fear, .hope]),
        scv("Psalms", 23, 5, 5, "Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.", "A meal set out calmly while the trouble is still in the room.", [.provision, .rest]),
        scv("Psalms", 23, 6, 6, "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever.", "The psalm ends where a wandering shepherd would want to end, at home.", [.mercy, .hope]),
        scv("Psalms", 24, 1, 1, "The earth is the LORD's, and the fulness thereof; the world, and they that dwell therein.", "A sentence that quietly resets who owns what.", [.humility, .praise]),
        scv("Psalms", 25, 4, 4, "Shew me thy ways, O LORD; teach me thy paths.", "A short request from someone willing to be taught slowly.", [.guidance, .humility]),
        scv("Psalms", 27, 1, 1, "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?", "Fear is answered here with a question rather than an argument.", [.fear, .hope]),
        scv("Psalms", 27, 14, 14, "Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD.", "The repetition suggests waiting was hard even then.", [.endurance, .hope]),
        scv("Psalms", 28, 7, 7, "The LORD is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him.", "Help received turns into a song, which is how many psalms began.", [.praise, .thanksgiving]),
        scv("Psalms", 29, 11, 11, "The LORD will give strength unto his people; the LORD will bless his people with peace.", "A psalm full of thunder ends on the word peace.", [.rest, .provision]),
        scv("Psalms", 30, 5, 5, "For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning.", "Written for the dedication of a house, after a long illness.", [.hope, .endurance]),
        scv("Psalms", 31, 24, 24, "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.", "Courage here is asked of a whole congregation, not one hero.", [.endurance, .hope]),
        scv("Psalms", 32, 1, 1, "Blessed is he whose transgression is forgiven, whose sin is covered.", "David begins his song of confession with relief, not shame.", [.mercy, .praise]),
        scv("Psalms", 32, 8, 8, "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.", "Guidance close enough to be given by a glance.", [.guidance, .love]),
        scv("Psalms", 34, 4, 4, "I sought the LORD, and he heard me, and delivered me from all my fears.", "David wrote this after escaping a king by feigning madness.", [.fear, .thanksgiving]),
        scv("Psalms", 34, 8, 8, "O taste and see that the LORD is good: blessed is the man that trusteth in him.", "An invitation to try rather than to be convinced.", [.hope, .praise]),
        scv("Psalms", 34, 18, 18, "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.", "Nearness is promised to the ones least able to feel it.", [.mercy, .love]),
        scv("Psalms", 37, 3, 3, "Trust in the LORD, and do good; so shalt thou dwell in the land, and verily thou shalt be fed.", "Trusting and doing good are set side by side, not in sequence.", [.provision, .guidance]),
        scv("Psalms", 37, 4, 4, "Delight thyself also in the LORD; and he shall give thee the desires of thine heart.", "Delight tends to reshape what a heart asks for.", [.love, .hope]),
        scv("Psalms", 37, 5, 5, "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.", "A line for a decision already made and now handed over.", [.guidance, .rest]),
        scv("Psalms", 37, 23, 23, "The steps of a good man are ordered by the LORD: and he delighteth in his way.", "Steps, not leaps, are what is described as ordered.", [.guidance, .endurance]),
        scv("Psalms", 40, 1, 1, "I waited patiently for the LORD; and he inclined unto me, and heard my cry.", "The waiting is mentioned first, and it was not short.", [.endurance, .hope]),
        scv("Psalms", 42, 1, 1, "As the hart panteth after the water brooks, so panteth my soul after thee, O God.", "The image is a thirsty deer, written by someone far from home.", [.doubt, .love]),
        scv("Psalms", 42, 5, 5, "Why art thou cast down, O my soul? and why art thou disquieted in me? hope thou in God: for I shall yet praise him for the help of his countenance.", "The writer speaks to himself, which is sometimes the only voice available.", [.doubt, .hope]),
        scv("Psalms", 46, 1, 1, "God is our refuge and strength, a very present help in trouble.", "Present is the working word, more than refuge or strength.", [.fear, .hope]),
        scv("Psalms", 46, 10, 10, "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.", "Spoken in a psalm about mountains shaking and wars ending.", [.rest, .humility]),
        scv("Psalms", 51, 10, 10, "Create in me a clean heart, O God; and renew a right spirit within me.", "David asks for something made new rather than merely repaired.", [.mercy, .humility]),
        scv("Psalms", 51, 17, 17, "The sacrifices of God are a broken spirit: a broken and a contrite heart, O God, thou wilt not despise.", "What a person is ashamed of is named as the acceptable offering.", [.humility, .mercy]),
        scv("Psalms", 55, 22, 22, "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.", "Written by a man betrayed by a close friend.", [.rest, .endurance]),
        scv("Psalms", 56, 3, 3, "What time I am afraid, I will trust in thee.", "Trust is placed inside the fear here, not after it.", [.fear, .hope]),
        scv("Psalms", 61, 2, 2, "From the end of the earth will I cry unto thee, when my heart is overwhelmed: lead me to the rock that is higher than I.", "A prayer for a vantage point above one's own strength.", [.doubt, .guidance]),
        scv("Psalms", 62, 5, 5, "My soul, wait thou only upon God; for my expectation is from him.", "Again the psalmist gives his own soul an instruction.", [.rest, .endurance]),
        scv("Psalms", 62, 8, 8, "Trust in him at all times; ye people, pour out your heart before him: God is a refuge for us. Selah.", "Pouring out suggests nothing needs to be tidied first.", [.hope, .rest]),
        scv("Psalms", 63, 1, 1, "O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is;", "Composed in the wilderness of Judah, where the thirst was literal.", [.love, .endurance]),
        scv("Psalms", 73, 26, 26, "My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever.", "Asaph admits the failing before he names the strength.", [.endurance, .hope]),
        scv("Psalms", 84, 11, 11, "For the LORD God is a sun and shield: the LORD will give grace and glory: no good thing will he withhold from them that walk uprightly.", "Warmth and protection are held together in one image.", [.provision, .mercy]),
        scv("Psalms", 86, 5, 5, "For thou, Lord, art good, and ready to forgive; and plenteous in mercy unto all them that call upon thee.", "Ready is a small word carrying most of the comfort.", [.mercy, .love]),
        scv("Psalms", 86, 11, 11, "Teach me thy way, O LORD; I will walk in thy truth: unite my heart to fear thy name.", "A divided heart is treated as a thing worth praying about.", [.guidance, .humility]),
        scv("Psalms", 90, 12, 12, "So teach us to number our days, that we may apply our hearts unto wisdom.", "Attributed to Moses, who watched a generation pass in the desert.", [.wisdom, .humility]),
        scv("Psalms", 91, 1, 1, "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.", "Dwelling suggests a habit rather than an emergency visit.", [.rest, .hope]),
        scv("Psalms", 91, 4, 4, "He shall cover thee with his feathers, and under his wings shalt thou trust: his truth shall be thy shield and buckler.", "A bird sheltering its young sits beside the image of armour.", [.love, .fear]),
        scv("Psalms", 91, 11, 11, "For he shall give his angels charge over thee, to keep thee in all thy ways.", "Keeping is described as ordinary care over ordinary routes.", [.provision, .hope]),
        scv("Psalms", 94, 19, 19, "In the multitude of my thoughts within me thy comforts delight my soul.", "A verse for a crowded mind late at night.", [.doubt, .rest]),
        scv("Psalms", 100, 4, 4, "Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name.", "Thanksgiving is pictured as the way in, not the reward.", [.thanksgiving, .praise]),
        scv("Psalms", 100, 5, 5, "For the LORD is good; his mercy is everlasting; and his truth endureth to all generations.", "Three short claims that carry the weight of the whole psalm.", [.mercy, .praise]),
        scv("Psalms", 103, 1, 1, "Bless the LORD, O my soul: and all that is within me, bless his holy name.", "David calls up his own gratitude rather than waiting for it.", [.praise, .thanksgiving]),
        scv("Psalms", 103, 8, 8, "The LORD is merciful and gracious, slow to anger, and plenteous in mercy.", "An echo of the words spoken to Moses on the mountain.", [.mercy, .love]),
        scv("Psalms", 103, 12, 12, "As far as the east is from the west, so far hath he removed our transgressions from us.", "The measurement chosen is the one with no midpoint.", [.mercy, .hope]),
        scv("Psalms", 103, 13, 13, "Like as a father pitieth his children, so the LORD pitieth them that fear him.", "The comparison is domestic and easy to picture.", [.love, .mercy]),
        scv("Psalms", 107, 1, 1, "O give thanks unto the LORD, for he is good: for his mercy endureth for ever.", "The opening of a psalm about travellers, prisoners and sailors.", [.thanksgiving, .mercy]),
        scv("Psalms", 118, 6, 6, "The LORD is on my side; I will not fear: what can man do unto me?", "A pilgrim song sung on the road to the feast.", [.fear, .hope]),
        scv("Psalms", 118, 24, 24, "This is the day which the LORD hath made; we will rejoice and be glad in it.", "Said of one particular day, and useful for any of them.", [.thanksgiving, .praise]),
        scv("Psalms", 119, 11, 11, "Thy word have I hid in mine heart, that I might not sin against thee.", "Memory is treated here as a practical safeguard.", [.wisdom, .discipline]),
        scv("Psalms", 119, 105, 105, "Thy word is a lamp unto my feet, and a light unto my path.", "An oil lamp lit only the next step, which is the point.", [.guidance, .wisdom]),
        scv("Psalms", 119, 114, 114, "Thou art my hiding place and my shield: I hope in thy word.", "Shelter and defense named together by someone under pressure.", [.hope, .fear]),
        scv("Psalms", 121, 1, 2, "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD, which made heaven and earth.", "A traveller's psalm, sung while looking at unsafe country.", [.hope, .guidance]),
        scv("Psalms", 121, 7, 8, "The LORD shall preserve thee from all evil: he shall preserve thy soul. The LORD shall preserve thy going out and thy coming in from this time forth, and even for evermore.", "Leaving and returning are both named, which covers most of a life.", [.provision, .rest]),
        scv("Psalms", 126, 5, 5, "They that sow in tears shall reap in joy.", "Sowing and reaping are separated by a season no one can shorten.", [.endurance, .hope]),
        scv("Psalms", 127, 1, 1, "Except the LORD build the house, they labour in vain that build it: except the LORD keep the city, the watchman waketh but in vain.", "A caution against effort that has quietly become anxious.", [.humility, .rest]),
        scv("Psalms", 130, 5, 5, "I wait for the LORD, my soul doth wait, and in his word do I hope.", "The waiting is said twice, as if the writer needed to hear it.", [.endurance, .hope]),
        scv("Psalms", 133, 1, 1, "Behold, how good and how pleasant it is for brethren to dwell together in unity!", "Sung by pilgrims arriving together after separate journeys.", [.love, .praise]),
        scv("Psalms", 138, 8, 8, "The LORD will perfect that which concerneth me: thy mercy, O LORD, endureth for ever: forsake not the works of thine own hands.", "Unfinished things are handed back to the one who started them.", [.hope, .mercy]),
        scv("Psalms", 139, 7, 8, "Whither shall I go from thy spirit? or whither shall I flee from thy presence? If I ascend up into heaven, thou art there: if I make my bed in hell, behold, thou art there.", "The psalmist tests the limits and cannot find one.", [.hope, .fear]),
        scv("Psalms", 139, 14, 14, "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.", "A line about the body, written with wonder rather than vanity.", [.praise, .thanksgiving]),
        scv("Psalms", 139, 23, 24, "Search me, O God, and know my heart: try me, and know my thoughts: And see if there be any wicked way in me, and lead me in the way everlasting.", "An invitation to be examined, offered without conditions.", [.humility, .guidance]),
        scv("Psalms", 143, 8, 8, "Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk; for I lift up my soul unto thee.", "A morning prayer from a man in hiding.", [.guidance, .love]),
        scv("Psalms", 145, 8, 8, "The LORD is gracious, and full of compassion; slow to anger, and of great mercy.", "Slowness is listed among the qualities worth praising.", [.mercy, .praise]),
        scv("Psalms", 145, 18, 18, "The LORD is nigh unto all them that call upon him, to all that call upon him in truth.", "Honesty is the only qualification named.", [.hope, .humility]),
        scv("Psalms", 146, 5, 5, "Happy is he that hath the God of Jacob for his help, whose hope is in the LORD his God.", "Jacob is named, a man remembered for limping and struggling.", [.hope, .praise]),
        scv("Psalms", 147, 3, 3, "He healeth the broken in heart, and bindeth up their wounds.", "Binding up is slow, careful work, and that is the picture.", [.mercy, .love]),
        scv("Psalms", 150, 6, 6, "Let every thing that hath breath praise the LORD. Praise ye the LORD.", "The last line of the psalter, and the simplest.", [.praise, .thanksgiving]),

        // MARK: - Proverbs

        scv("Proverbs", 1, 7, 7, "The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction.", "The book states its starting point before offering any advice.", [.wisdom, .humility]),
        scv("Proverbs", 2, 6, 6, "For the LORD giveth wisdom: out of his mouth cometh knowledge and understanding.", "Wisdom is described as received, not only earned.", [.wisdom, .provision]),
        scv("Proverbs", 3, 5, 6, "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.", "Leaning is what a person does without noticing.", [.guidance, .humility]),
        scv("Proverbs", 3, 11, 12, "My son, despise not the chastening of the LORD; neither be weary of his correction: For whom the LORD loveth he correcteth; even as a father the son in whom he delighteth.", "Correction is set inside affection rather than opposed to it.", [.discipline, .love]),
        scv("Proverbs", 4, 7, 7, "Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding.", "A father speaks, ranking one pursuit above the rest.", [.wisdom, .discipline]),
        scv("Proverbs", 4, 18, 18, "But the path of the just is as the shining light, that shineth more and more unto the perfect day.", "Growing light, not sudden light, is the picture offered.", [.hope, .endurance]),
        scv("Proverbs", 4, 23, 23, "Keep thy heart with all diligence; for out of it are the issues of life.", "What is guarded inwardly tends to show up outwardly.", [.wisdom, .discipline]),
        scv("Proverbs", 6, 6, 6, "Go to the ant, thou sluggard; consider her ways, and be wise:", "The teacher sends the student outdoors to watch something small.", [.discipline, .wisdom]),
        scv("Proverbs", 9, 10, 10, "The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding.", "Reverence is treated as a first step, not a final exam.", [.wisdom, .humility]),
        scv("Proverbs", 10, 12, 12, "Hatred stirreth up strifes: but love covereth all sins.", "Two responses to the same offence, with different results.", [.love, .mercy]),
        scv("Proverbs", 10, 19, 19, "In the multitude of words there wanteth not sin: but he that refraineth his lips is wise.", "Saying less is offered as a plain, workable discipline.", [.wisdom, .discipline]),
        scv("Proverbs", 11, 2, 2, "When pride cometh, then cometh shame: but with the lowly is wisdom.", "The pairing suggests one arrival brings the other along.", [.humility, .wisdom]),
        scv("Proverbs", 11, 14, 14, "Where no counsel is, the people fall: but in the multitude of counsellers there is safety.", "Advice from several people is treated as a safeguard.", [.wisdom, .guidance]),
        scv("Proverbs", 12, 15, 15, "The way of a fool is right in his own eyes: but he that hearkeneth unto counsel is wise.", "Being sure of yourself is not the same as being right.", [.humility, .wisdom]),
        scv("Proverbs", 12, 25, 25, "Heaviness in the heart of man maketh it stoop: but a good word maketh it glad.", "A kind sentence is described as having physical effect.", [.love, .hope]),
        scv("Proverbs", 13, 20, 20, "He that walketh with wise men shall be wise: but a companion of fools shall be destroyed.", "Company is treated as slow instruction either way.", [.wisdom, .guidance]),
        scv("Proverbs", 14, 29, 29, "He that is slow to wrath is of great understanding: but he that is hasty of spirit exalteth folly.", "Speed of temper is read as a measure of understanding.", [.discipline, .wisdom]),
        scv("Proverbs", 15, 1, 1, "A soft answer turneth away wrath: but grievous words stir up anger.", "The tone of a reply is doing most of the work.", [.humility, .love]),
        scv("Proverbs", 15, 22, 22, "Without counsel purposes are disappointed: but in the multitude of counsellers they are established.", "Plans are said to need other people before they hold.", [.wisdom, .guidance]),
        scv("Proverbs", 15, 33, 33, "The fear of the LORD is the instruction of wisdom; and before honour is humility.", "The order of those last two words is the whole lesson.", [.humility, .wisdom]),
        scv("Proverbs", 16, 3, 3, "Commit thy works unto the LORD, and thy thoughts shall be established.", "Handing over the work is said to settle the mind.", [.rest, .guidance]),
        scv("Proverbs", 16, 9, 9, "A man's heart deviseth his way: but the LORD directeth his steps.", "Planning is not discouraged, only put in its place.", [.guidance, .humility]),
        scv("Proverbs", 16, 18, 18, "Pride goeth before destruction, and an haughty spirit before a fall.", "One of the few proverbs most people can quote from memory.", [.humility, .discipline]),
        scv("Proverbs", 16, 32, 32, "He that is slow to anger is better than the mighty; and he that ruleth his spirit than he that taketh a city.", "Self-command is ranked above military success.", [.discipline, .humility]),
        scv("Proverbs", 17, 17, 17, "A friend loveth at all times, and a brother is born for adversity.", "Friendship is measured by what it does in bad weather.", [.love, .endurance]),
        scv("Proverbs", 17, 22, 22, "A merry heart doeth good like a medicine: but a broken spirit drieth the bones.", "Cheerfulness is spoken of as something physical.", [.hope, .rest]),
        scv("Proverbs", 18, 10, 10, "The name of the LORD is a strong tower: the righteous runneth into it, and is safe.", "A tower only helps the person willing to run.", [.fear, .hope]),
        scv("Proverbs", 18, 21, 21, "Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof.", "Ordinary speech is given remarkable weight here.", [.wisdom, .discipline]),
        scv("Proverbs", 18, 24, 24, "A man that hath friends must shew himself friendly: and there is a friend that sticketh closer than a brother.", "Friendship is presented as something to be offered first.", [.love, .endurance]),
        scv("Proverbs", 19, 11, 11, "The discretion of a man deferreth his anger; and it is his glory to pass over a transgression.", "Letting something go is called an honour, not a loss.", [.mercy, .humility]),
        scv("Proverbs", 19, 21, 21, "There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand.", "Useful on a day when plans have quietly collapsed.", [.guidance, .hope]),
        scv("Proverbs", 22, 1, 1, "A good name is rather to be chosen than great riches, and loving favour rather than silver and gold.", "Reputation is weighed here against money and preferred.", [.wisdom, .humility]),
        scv("Proverbs", 22, 6, 6, "Train up a child in the way he should go: and when he is old, he will not depart from it.", "A long view of parenting, measured in decades.", [.guidance, .love]),
        scv("Proverbs", 24, 16, 16, "For a just man falleth seven times, and riseth up again: but the wicked shall fall into mischief.", "The falling is expected; the rising is what is noticed.", [.endurance, .hope]),
        scv("Proverbs", 25, 11, 11, "A word fitly spoken is like apples of gold in pictures of silver.", "Timing, not volume, is what makes the word valuable.", [.wisdom, .love]),
        scv("Proverbs", 25, 21, 21, "If thine enemy be hungry, give him bread to eat; and if he be thirsty, give him water to drink:", "Practical kindness is asked for before any feeling changes.", [.mercy, .love]),
        scv("Proverbs", 27, 1, 1, "Boast not thyself of to morrow; for thou knowest not what a day may bring forth.", "A quiet check on confident scheduling.", [.humility, .wisdom]),
        scv("Proverbs", 27, 17, 17, "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.", "Sharpening involves friction, which the image does not hide.", [.wisdom, .love]),
        scv("Proverbs", 28, 13, 13, "He that covereth his sins shall not prosper: but whoso confesseth and forsaketh them shall have mercy.", "Concealment is described as the more exhausting option.", [.mercy, .humility]),
        scv("Proverbs", 29, 23, 23, "A man's pride shall bring him low: but honour shall uphold the humble in spirit.", "Each disposition is said to carry its own outcome.", [.humility, .justice]),
        scv("Proverbs", 29, 25, 25, "The fear of man bringeth a snare: but whoso putteth his trust in the LORD shall be safe.", "Worrying about opinion is pictured as a trap underfoot.", [.fear, .hope]),
        scv("Proverbs", 30, 5, 5, "Every word of God is pure: he is a shield unto them that put their trust in him.", "Agur, a writer we know almost nothing about, says this.", [.wisdom, .hope]),
        scv("Proverbs", 31, 8, 9, "Open thy mouth for the dumb in the cause of all such as are appointed to destruction. Open thy mouth, judge righteously, and plead the cause of the poor and needy.", "Advice given to a king by his mother.", [.justice, .mercy]),
        scv("Proverbs", 31, 25, 25, "Strength and honour are her clothing; and she shall rejoice in time to come.", "The portrait ends with a woman unafraid of the future.", [.endurance, .hope]),
        scv("Proverbs", 31, 26, 26, "She openeth her mouth with wisdom; and in her tongue is the law of kindness.", "Wisdom and kindness are named together, as one habit.", [.wisdom, .love]),

        // MARK: - Ecclesiastes

        scv("Ecclesiastes", 1, 2, 2, "Vanity of vanities, saith the Preacher, vanity of vanities; all is vanity.", "The old word vanity here means vapour, something hard to hold.", [.humility, .doubt]),
        scv("Ecclesiastes", 3, 1, 1, "To every thing there is a season, and a time to every purpose under the heaven:", "The opening of a list that refuses to rank its seasons.", [.wisdom, .rest]),
        scv("Ecclesiastes", 3, 4, 4, "A time to weep, and a time to laugh; a time to mourn, and a time to dance;", "Grief and celebration are given equal standing.", [.endurance, .hope]),
        scv("Ecclesiastes", 3, 7, 7, "A time to rend, and a time to sew; a time to keep silence, and a time to speak;", "Silence is listed as a choice, not a failure to answer.", [.wisdom, .discipline]),
        scv("Ecclesiastes", 3, 11, 11, "He hath made every thing beautiful in his time: also he hath set the world in their heart, so that no man can find out the work that God maketh from the beginning to the end.", "A rare moment of rest in a restless book.", [.hope, .humility]),
        scv("Ecclesiastes", 4, 9, 10, "Two are better than one; because they have a good reward for their labour. For if they fall, the one will lift up his fellow: but woe to him that is alone when he falleth; for he hath not another to help him up.", "The argument for company is made in plain practical terms.", [.love, .endurance]),
        scv("Ecclesiastes", 4, 12, 12, "And if one prevail against him, two shall withstand him; and a threefold cord is not quickly broken.", "Often read at weddings, though written about work.", [.love, .endurance]),
        scv("Ecclesiastes", 5, 2, 2, "Be not rash with thy mouth, and let not thine heart be hasty to utter any thing before God: for God is in heaven, and thou upon earth: therefore let thy words be few.", "Advice about prayer that recommends brevity.", [.humility, .wisdom]),
        scv("Ecclesiastes", 5, 10, 10, "He that loveth silver shall not be satisfied with silver; nor he that loveth abundance with increase: this is also vanity.", "The Preacher had the money and reports back honestly.", [.humility, .wisdom]),
        scv("Ecclesiastes", 7, 8, 8, "Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit.", "Finishing is quietly preferred to starting well.", [.endurance, .humility]),
        scv("Ecclesiastes", 7, 9, 9, "Be not hasty in thy spirit to be angry: for anger resteth in the bosom of fools.", "Anger is described as something that takes up residence.", [.discipline, .wisdom]),
        scv("Ecclesiastes", 9, 10, 10, "Whatsoever thy hand findeth to do, do it with thy might; for there is no work, nor device, nor knowledge, nor wisdom, in the grave, whither thou goest.", "A short life is used as an argument for present effort.", [.discipline, .endurance]),
        scv("Ecclesiastes", 11, 1, 1, "Cast thy bread upon the waters: for thou shalt find it after many days.", "Generosity is described without any guarantee of speed.", [.hope, .provision]),
        scv("Ecclesiastes", 12, 1, 1, "Remember now thy Creator in the days of thy youth, while the evil days come not, nor the years draw nigh, when thou shalt say, I have no pleasure in them;", "An older voice speaking directly to a younger one.", [.wisdom, .guidance]),
        scv("Ecclesiastes", 12, 13, 13, "Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the whole duty of man.", "After many pages of questions, the book lands on two things.", [.wisdom, .humility]),

        // MARK: - Job

        scv("Job", 1, 21, 21, "And said, Naked came I out of my mother's womb, and naked shall I return thither: the LORD gave, and the LORD hath taken away; blessed be the name of the LORD.", "Spoken on the worst day of his life, before the arguments began.", [.endurance, .praise]),
        scv("Job", 13, 15, 15, "Though he slay me, yet will I trust in him: but I will maintain mine own ways before him.", "Trust and protest are held together in a single sentence.", [.endurance, .doubt]),
        scv("Job", 14, 1, 1, "Man that is born of a woman is of few days, and full of trouble.", "Job states the case plainly, without softening it.", [.humility, .doubt]),
        scv("Job", 19, 25, 25, "For I know that my redeemer liveth, and that he shall stand at the latter day upon the earth:", "A moment of certainty in the middle of a long complaint.", [.hope, .endurance]),
        scv("Job", 23, 10, 10, "But he knoweth the way that I take: when he hath tried me, I shall come forth as gold.", "Said by a man who could not find God anywhere he looked.", [.endurance, .hope]),
        scv("Job", 28, 28, 28, "And unto man he said, Behold, the fear of the Lord, that is wisdom; and to depart from evil is understanding.", "A long poem about mining ends by locating wisdom elsewhere.", [.wisdom, .humility]),
        scv("Job", 38, 4, 4, "Where wast thou when I laid the foundations of the earth? declare, if thou hast understanding.", "God answers Job with questions rather than explanations.", [.humility, .doubt]),
        scv("Job", 38, 7, 7, "When the morning stars sang together, and all the sons of God shouted for joy?", "The making of the world is remembered as a celebration.", [.praise, .hope]),
        scv("Job", 42, 2, 2, "I know that thou canst do every thing, and that no thought can be withholden from thee.", "Job speaks last, and much shorter than before.", [.humility, .praise]),
        scv("Job", 42, 5, 5, "I have heard of thee by the hearing of the ear: but now mine eye seeth thee.", "He never receives his answer, but says this instead.", [.humility, .hope]),

        // MARK: - Lamentations

        scv("Lamentations", 3, 22, 22, "It is of the LORD's mercies that we are not consumed, because his compassions fail not.", "Written after the city fell, amid the ruins.", [.mercy, .hope]),
        scv("Lamentations", 3, 23, 23, "They are new every morning: great is thy faithfulness.", "The line that follows the ruin, and turns the whole book.", [.mercy, .thanksgiving]),
        scv("Lamentations", 3, 24, 24, "The LORD is my portion, saith my soul; therefore will I hope in him.", "Portion was the word for an inheritance of land.", [.hope, .provision]),
        scv("Lamentations", 3, 25, 25, "The LORD is good unto them that wait for him, to the soul that seeketh him.", "Waiting and seeking are named as one posture.", [.endurance, .hope]),
        scv("Lamentations", 3, 26, 26, "It is good that a man should both hope and quietly wait for the salvation of the LORD.", "Quietness is recommended by someone who had wept loudly.", [.rest, .endurance]),
    ]
}
